### ISSUE TITLE
Implement `Bounded`

### ISSUE THREAD

**Issue by WhyNotHugo** [jhpratt/deranged#7]
Is it feasible to implement [num_traits](https://docs.rs/num-traits/0.2.14/num_traits/index.html)::[bounds](https://docs.rs/num-traits/0.2.14/num_traits/bounds/index.html)::[Bounded](https://docs.rs/num-traits/0.2.14/num_traits/bounds/trait.Bounded.html)?

**Comment by jhpratt** [comment]
Yes, this could be done trivially. Are you actually using this crate? To my knowledge nobody actually does; there's certainly no reverse dependencies on crates.io.

My goal when creating this crate was twofold: I wanted to play around to see how it would work with pre-existing APIs and I wanted to see how feasible implementations were for stdlib. The third-party trait implementations that exist right now are because that's what I needed for my "playing around" use case.

**Comment by WhyNotHugo** [comment]
I used it for a small tool to control brightness -- where values are percentages (e.g.: ranged numbers from 1 to 100). But it's been parked for a long time TBH (hence, not published).

**Comment by jhpratt** [comment]
Okay! I'll get to this tonight. It should just be a few lines. It'll be behind the `num` feature gate.

**Comment by jhpratt** [comment]
Implemented and released.
